name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies (csharp)
      working-directory: 2020/csharp/Aoc2020CalendarTests
      run: dotnet restore
    - name: Build (csharp)
      working-directory: 2020/csharp/Aoc2020Calendar
      run: dotnet build --configuration Release --no-restore
    - name: Test (csharp)
      working-directory: 2020/csharp/Aoc2020CalendarTests
      run: dotnet test --configuration Release --no-restore --verbosity normal
